Fix image in Jetty Custom Variables #493
Onemind-Services-LLC/cloudmydc-docs pull request #612
Opened 2024-03-28 08:52 UTC by VKumar786

## Pull Request

Change Type Correction

Fixes #493

2024-03-28 15:39 UTC, abhi1693 approved these changes

2024-03-28 15:39 UTC, abhi1693 commented
Fix conflicts

2024-03-28 16:38 UTC, abhi1693 approved these changes

2024-04-23 09:33 UTC, yash-pal1 approved these changes

2024-04-23 09:36 UTC, yash-pal1 requested changes
second image should be glassfish node, not tomcat nod

2024-04-25 09:40 UTC, VKumar786 commented
@yash-pal1 now image are fixed, in old code image was wrong.

2024-04-26 12:31 UTC, yash-pal1 approved these changes

2024-04-26 12:31 UTC, merged